# The numpy.random Package

## An investigation into the numpy.random package or submodule in Python.
numpy provides various routines through its numpy.random submodule. In particular it uses an algorithm called the Mersenne Twister to generate random numbers.
The ability to generate random numbers is an important part of any simulation. Computers and even people cannot or find it difficult to generate really random numbers. For this reason the type of numbers generated on computers are pseudorandom.


## Simple random data
Some examples of this function in numpy.random

Basic form: rand(d0,d1,...,d0)

In [4]:
import numpy as np
np.random.rand(3,2)

array([[ 0.56563071,  0.50866289],
       [ 0.13659582,  0.21945505],
       [ 0.04712577,  0.38272524]])

Result: the command returns an array of 3 rows and 2 colomns of random numbers between 0 and 1

In [5]:
np.random.randn(2,3)

array([[ 0.04798651,  1.25878015,  0.4026655 ],
       [-0.55194222,  1.38839786,  1.09915041]])

Result:this command returns 2 rows and 3 columns of random numbers from the normal or Gaussian distribution

## Permutations
Permutation functions in the package are: shuffle(x) and permutation(x)

## Distributions function
There are many probability distributions in statistics. numpy.random can generate random values to model these distributions. We discuss 5 of them here;

## Uniform Distribution
Basic form: uniform([low, high, size])

In [7]:
np.random.uniform(0,10,3)

array([ 7.40733998,  9.17234279,  6.92906631])

Result: we get an array of size 3 numbers, randomly generated between 0 and 10. These numbers are almost even, hence the name uniform distribution

## Binomial Distribution
Basic form:binomial(n, p[, size])

In [8]:
np.random.binomial(5,0.1,6)

array([3, 0, 1, 1, 1, 0])

Result: an array of size 6, returning numbers between 0 and 5 with a probability of 0.1 or 10 per cent

## Normal Distribution
Basic form:normal([loc, scale, size])

In [9]:
np.random.normal(0,3,100)

array([-0.32685644, -2.39627928,  2.30335296,  2.30667463, -4.76383374,
        2.29436066,  4.30640487, -1.62799281, -3.19950173,  2.4180632 ,
       -0.78566209, -0.77860645,  1.61336297, -0.52014584, -2.49297677,
       -0.34123751, -2.06874545, -3.64733656,  2.76295624,  4.89929863,
        1.18564677,  4.44193138, -0.04675692, -5.39629816,  2.05142777,
        1.21387512,  2.81926917,  1.61092106,  1.5901842 ,  3.57983872,
       -2.37830257,  1.28333226, -2.69165402, -0.17552196, -0.18149963,
        1.60548836, -2.26162145, -2.21805898,  6.02960466, -1.23985555,
       -3.02874181,  0.26936625,  1.3143286 , -0.51759401,  1.26400524,
       -2.40529684,  0.94779815, -0.06918003,  2.44925539,  1.34705775,
       -0.43643941, -0.92204464,  0.67152028, -1.07094724, -3.40249704,
        1.77605681,  0.04714223, -2.32301197,  2.52935021,  2.62606771,
        0.55205428, -1.33379308, -1.8166441 ,  0.79242791,  2.89324164,
       -4.2056899 ,  1.36447494,  3.49331764, -2.29704942,  0.46

Result: an array of 100 elements (numbers) of the standard normal, or Gaussian Distribution. The mean is given as 0, the standard deviation is 3. The spread about the mean is therefore between -3 and 3. Some numbers are on the 'tail' outside of this range.

## Exponential Distribution
Basic form : exponential([scale, size])

In [10]:
np.random.exponential(1,2)

array([ 0.453594 ,  0.2991479])

Result: a set of 2 randomly generated numbers of the exponential distribution

## Geometric Distribution
Basic form: geometric(p[, size])

In [15]:
np.random.geometric(0.2,10)

array([ 6,  1,  5,  4, 11, 14,  1,  1,  6, 11])

Result: a set of 10 random numbers corresponding with our choice of 10 as the size. These numbers have a probability of 0.2 or 20 per cent of occurring

## Seeds in generating pseudorandom numbers
As mentioned above, computers cannot generate pure random numbers. They have to generate pseudorandom values. A seed is the key or starting point in a sequence of random number generation. This 'key' is usually the time in microseconds when the computer was switched on. It follows from this starting point in a sequence that other random numbers will follow. The seed is the first value, to be followed by others in pseudorandom order. For example the RandomState function in numpy.random is a generator of pseudorandom numbers based on the Mersenne Twister (a number based anywhere between 0 and a Mersenne prime, 2**32-1).
